# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: capv-controller-manager
#   namespace: capv-system
# spec:
#   template:
#     spec:
#       containers:
#       - name: manager
#         image: TODO
#       tolerations:
#       - effect: NoSchedule
#         key: node-role.kubernetes.io/master
#       - key: CriticalAddonsOnly
#         operator: Exists
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cabpk-controller-manager
  namespace: cabpk-system
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
      - name: manager
        image: us.gcr.io/k8s-artifacts-prod/capi-kubeadm/cluster-api-kubeadm-controller:v0.1.0
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-controller-manager
  namespace: capi-system
spec:
  template:
    spec:
      containers:
      - name: manager
        image: us.gcr.io/k8s-artifacts-prod/cluster-api/cluster-api-controller:v0.2.1
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
