
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: vultrmachines.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    kind: VultrMachine
    listKind: VultrMachineList
    plural: vultrmachines
    singular: vultrmachine
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VultrMachine is the Schema for the vultrmachines API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VultrMachineSpec defines the desired state of VultrMachine
          properties:
            osID:
              description: OSID is the id of operating system (OSID).
              type: integer
            planID:
              description: PlanID is the id of Vultr VPS plan (VPSPLANID).
              type: integer
            providerID:
              description: ProviderID is the unique identifer as specified by the
                cloud provider.
              type: string
            scriptID:
              description: ScriptID is the id of Startup Script (SCRIPTID).
              type: integer
            sshKeyName:
              description: SSHKeyName is the name of the ssh key to attach to the
                instance.
              type: string
          type: object
        status:
          description: VultrMachineStatus defines the observed state of VultrMachine
          properties:
            powerStatus:
              description: PowerStatus represents that the VPS is powerd on or not
              type: string
            ready:
              description: Ready represents the infrastructure is ready to be used
                or not.
              type: boolean
            serverState:
              description: ServerState represents a detail of server state.
              type: string
            subscriptionStatus:
              description: ServerStatus represents the status of subscription.
              type: string
          required:
          - ready
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
