
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: vultrclusters.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    kind: VultrCluster
    listKind: VultrClusterList
    plural: vultrclusters
    singular: vultrcluster
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VultrCluster is the Schema for the vultrclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VultrClusterSpec defines the desired state of VultrCluster
          properties:
            region:
              description: The Vultr Region (DCID) the cluster lives in.
              type: integer
          required:
          - region
          type: object
        status:
          description: VultrClusterStatus defines the observed state of VultrCluster
          properties:
            apiEndpoints:
              items:
                description: APIEndpoint represents control-plane's apiserver endpoints.
                properties:
                  host:
                    description: The hostname on which the API server is serving.
                    type: string
                  port:
                    description: The port on which the API server is serving.
                    type: integer
                required:
                - host
                - port
                type: object
              type: array
            ready:
              type: boolean
          required:
          - ready
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
